config/routes.rb
Rails.application.routes.draw do
  resources :games
  # Essentially:
  # get   '/games'          => 'games#index'
  # get   '/games/:id'      => 'games#show'
  # post  '/games'          => 'games#create'
  # patch '/games/:id'      => 'games#update'
  # get   '/games/new'      => 'games#new'
  # get   '/games/:id/edit' => 'games#edit'
  # delete '/games/:id'     => 'games#destroy'
  # w/ slightly different URL helpers

  get  '/'            => 'users#select'
  post '/change_user' => 'users#change'
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id         :integer          not null, primary key
#  answer     :string(255)
#  max_misses :integer
#  misses     :integer
#  guessed    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Game < ActiveRecord::Base
  # ^ knows to look at "games" table for data
  #   and defines methods from schema
  belongs_to :user

  # Answer cannot be nil or ""
  validates_presence_of :answer, :max_misses, :misses
  validate :guessed_string_is_not_nil

  def board
    result = ""
    self.answer.split("").each do |char|
      if self.guessed.include?(char)
        result += char
      else
        result += "_"
      end
    end
    result
  end

  def guess(letter)
    letter.downcase!
    found = self.answer.include?(letter)

    unless self.guessed.include?(letter)
      self.guessed += letter
      self.misses += 1 unless found
    end
    self.save!

    found
  end

  def guessed_string_is_not_nil
    if guessed.nil?
      self.errors.add :guessed, "Guessed cannot be nil"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find session[:selected_user]
  end
end

app/controllers/games_controller.rb
# Note the plural
class GamesController < ApplicationController
  def index # display a _collection_ of games
    # Equivalent:
    #   @games = Game.where(user_id: user.id)
    @games = current_user.games
  end

  def show
    id = params[:id]
    @game = current_user.games.find(id)
  end

  def create
    random_word = File.read(__FILE__).
      split(" ").reject{ |word| word.length < 5 }.sample

    game = current_user.games.create!(
      max_misses: 10,
      misses:     0,
      answer:     random_word,
      guessed:    ""
    )
    redirect_to game
  end

  def update
    game = current_user.games.find params[:id]
    game.guess params[:letter]
    redirect_to game
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def select
    @users = User.all
  end

  def change
    # "Permanently" stores the selected user in the
    #   session
    # For this user, for this browsing session
    session[:selected_user] = params[:selected_user]
    redirect_to games_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.haml
%h1 Hangman Games

%table.table.table-striped.table-bordered
  %thead
    %tr
      %th ID
      %th Board
      %th Status
  %tbody
    - @games.each do |game|
      %tr
        %td= link_to game.id, game
        %td= game.board
        %td= "#{game.misses} / #{game.max_misses}"

= button_to "New Game", games_path, method: :post

app/views/games/show.html.haml
%pre= @game.board

%h3 Status
%p
  = "#{@game.misses} / #{@game.max_misses} misses"

%h3 Guessed
%p
  = @game.guessed

= form_tag(game_path(@game), method: "patch") do
  = text_field_tag "letter"
  = submit_tag "Guess"

= link_to "Back", games_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hangme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/users/select.html.haml
= form_tag(change_user_path, method: :post) do
  %select{ name: :selected_user }
    / %option{ value: 1 } James Dabbs
    / %option{ value: 2 } Dan Cornnell
    - @users.each do |user|
      %option{ value: user.id }= user.name
  %button Login